name: CoMameDobreho
options:
  bundleIdPrefix: com.codobreho
  deploymentTarget:
    iOS: 11.0
  xcodeVersion: "12.3"
packages:
  CouchbaseLiteSwift:
    url: https://github.com/couchbase/couchbase-lite-ios
    version: 2.8.1
  Eureka:
    url: https://github.com/xmartlabs/Eureka
    version: 5.3.2
  SwifterSwift:
    url: https://github.com/SwifterSwift/SwifterSwift
    version: 5.2.0
targets:
  CoMameDobrehoApp:
    type: application
    platform: iOS
    sources: [CoMameDobreho]
    dependencies:
      - package: CouchbaseLiteSwift
      - package: Eureka
      - package: SwifterSwift
    info:
      path: CoMameDobreho/Info.plist
      properties:
        NSBluetoothAlwaysUsageDescription: "TODO"
        UISupportedInterfaceOrientations: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationPortraitUpsideDown,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight
        ]
    preBuildScripts:
      - script: "mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.3"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
